# Generated by Django 2.2.12 on 2020-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200509_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description_small', models.CharField(max_length=200, null='No SMALL description provided')),
                ('description_big', models.CharField(max_length=1000, null='No BIG description provided')),
                ('price', models.FloatField(null=True)),
                ('number_available', models.IntegerField(null=True)),
                ('image_file', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
    ]
