# Generated by Django 2.2.12 on 2020-05-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
