# Generated by Django 2.2.12 on 2020-05-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200509_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='author',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description_big',
            field=models.CharField(max_length=4000, null='No BIG description provided'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description_small',
            field=models.CharField(max_length=122, null='No SMALL description provided'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
