# Generated by Django 2.2.12 on 2020-05-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200509_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, null=True)),
                ('description_small', models.CharField(max_length=200, null='No SMALL description provided')),
                ('description_big', models.CharField(max_length=4000, null='No BIG description provided')),
                ('photo', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
        migrations.AlterField(
            model_name='painting',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
