# Generated by Django 2.2.12 on 2020-05-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200509_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='author',
        ),
    ]
