# Generated by Django 2.2.12 on 2020-05-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_painting_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='author',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
