# Generated by Django 2.2.12 on 2020-05-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200509_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='author',
            new_name='author1',
        ),
    ]
