# Generated by Django 2.2.12 on 2020-05-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200509_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='author1',
        ),
    ]
