# Generated by Django 2.2.12 on 2020-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_painting_author1'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='author',
            field=models.CharField(max_length=144, null=True),
        ),
    ]
