# Generated by Django 2.2.12 on 2020-05-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_painting_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
