# Generated by Django 2.2.12 on 2020-05-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200509_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Artist',
        ),
    ]
