# Generated by Django 2.2.12 on 2020-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200510_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='quote',
            field=models.CharField(max_length=400, null='No QUOTES provided'),
            preserve_default='No QUOTES provided',
        ),
    ]
