# Generated by Django 2.2.12 on 2020-05-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
