# Generated by Django 2.2.12 on 2020-05-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Customer'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
