# Generated by Django 2.2.12 on 2020-05-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200511_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
