# Generated by Django 2.2.12 on 2020-05-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_customer_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_caption', models.CharField(max_length=100, verbose_name='Заголовок сообщения')),
                ('email_text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('email_date', models.DateField(null=True, verbose_name='Время отправки')),
                ('email_time', models.TimeField(null=True)),
                ('resp', models.ManyToManyField(limit_choices_to={'verified': True}, to='blog.Customer')),
            ],
        ),
    ]
