# Generated by Django 2.2.12 on 2020-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20200513_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymail',
            name='check_send',
            field=models.BooleanField(default=False),
        ),
    ]
