# Generated by Django 2.2.12 on 2020-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_mymail_check_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='verified',
        ),
        migrations.AddField(
            model_name='customer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
