# Generated by Django 2.2.12 on 2020-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20200514_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='quote',
            field=models.TextField(default='No QUOTES provided', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description_big',
            field=models.CharField(default='No BIG description provided', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description_small',
            field=models.CharField(default='No SMALL description provided', max_length=122, null=True),
        ),
    ]
