# Generated by Django 2.2.12 on 2020-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20200515_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='quote',
            field=models.TextField(default='No QUOTES provided', max_length=400),
        ),
    ]
