# Generated by Django 2.2.12 on 2020-05-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20200517_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
