# Generated by Django 2.2.12 on 2020-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20200517_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=40, null=True),
        ),
    ]
